### ISSUE TITLE
Call for Testing/Feedback: howler.js v2.0.0-beta

### ISSUE THREAD

**Issue by goldfire** [goldfire/howler.js#193]
The `2.0` branch is finally to a point where it is ready for public testing and feedback! This is still very much beta, so use at your own risk (especially the effects plugin). The library has been rewritten from the ground up, taking into account all of the lessons learned since the very first commit. Be sure to check the changelog for the quite large list of additions/updates/fixes.

Before this can be merged to master, I need help from the community testing and providing feedback on the API, features, etc. Please use this thread for general feedback and tag any issues or pull requests with `2.0`. There's still a lot of work to be done, so check back with this thread often for updates.

There's also a new audible testing script in the `tests` directory. I'd love to expand this further, so if anyone has ideas, please add them here or open a pull request. Be sure to run the tests on a webserver so that the Web Audio section doesn't fall back to HTML5 Audio.

### TODO
- [x] Determine what else is missing from effects plugin.
- [x] Clear out rest of open 2.0 issues.
- [x] Improvements to tests.
- [x] Overhaul the documentation.
- [x] Add more examples to documentation.
- [x] New examples and demos.
- [x] Create a migration guide.
- [x] Should the logo get a refresh?

...am I forgetting anything?

**Comment by gre** [comment]
Thanks for this v2, it works quite smooth on my current game, 3D audio is a blast, very impressive result.

I have feedbacks in term of API, I don't find it very easy and straightforward to use `audioId` that you have to pass in to all functions:

```javascript
var audioId = howl.play();
howl.pos(x, y, z, audioId);
howl.velocity(vx, vy, vz, audioId);
```

I don't know what are the reason behind but I I think it would be simpler to have an object returned like:

```javascript
var soundInstance = howl.play();
soundInstance.pos(x, y, z);
soundInstance.velocity(vx, vy, vz);
```


Also, it would be great to be able to do this:

```javascript
var soundInstance = howl.play({ pos: [x,y,z], velocity: [vx,vy,vz] });
```

That would make it more obvious (and maybe on your side have more guarantee) that the play() will start at a given **pos** and **velocity** (and no click / jump after starting the sound – if you happen to have this bug in the future, the current API make it impossible to fix that because you play before setting pos and velocity).

Also, in general, my proposal could be a way to unify the API of the listener, the group and a sound instance:

```javascript
// 3 use-cases, same API
howl.pos(x, y, z);
soundInstance.pos(x, y, z);
Howler.pos(x, y, z); // like current, but ideally I think something like: `Howler.listener.pos(...)` would be more straightforward that you basically set the position of the microphone.
```

Thanks

**Comment by goldfire** [comment]
I've been revisiting my notes on the initial API choice from last summer (ouch, didn't realize it had been that long), and I may have come up with a way to use the cleaner API, while still allowing the current API to work, and adding in a few new benefits. I need to play around with the idea to see if it runs into any snags, but I'd still love to hear any thoughts on the API.

**Comment by gre** [comment]
Ok cool

**Comment by nyttimangus** [comment]
I just tried a basic sample of the beta in Windows 10's new Edge browser, and it seemed broken (as compared to performance in Chrome, Firefox, and IE). It sounded almost like the audio was being played on top of itself many many times.

**Comment by goldfire** [comment]
Just a quick update on where things are at. I've been in a fight for my startup's life since last fall, which is why the development on 2.0 slowly tapered out. However, we've finally hit our stride the last few months, and we've started hiring more developers. This is finally starting to give me a little more free time!

There's quite a few issues and pull requests I need to get caught up on. My plan is to get caught up on all of that over the next few weeks and then finally get on to finalizing and merging 2.0.

**Comment by nhoizey** [comment]
Any news for a stable 2.0?

**Comment by goldfire** [comment]
@nhoizey Getting very close on closing out the rest of the remaining issues. Other than that, before merging into master I'm going to create some more comprehensive examples, create a migration guide and possibly setup a standalone website rather than just a blog post. I'm finally getting some more free time now, so this should all start to come together much more quickly than the rest (I'll post more updates here over the next few weeks).

**Comment by nhoizey** [comment]
@goldfire good to read from you again, and know that it will come together more quickly now! ;-)

**Comment by goldfire** [comment]
Just a quick update. Virtually all of the issues marked for 2.0 have now been closed (woohoo!). The process has now mostly shifted towards setting up some example/demo projects (tracked in https://github.com/goldfire/howler.js/issues/444). I'm also in the process of setting up a proper website for howlerjs.com rather than just pointing to the blog post. I'm going to also try and get the migration guide posted soon as well as some other various bits of cleanup and polish to the 2.0 branch.

**Comment by goldfire** [comment]
We are getting really close now! The new website and logo are nearing completion, would appreciate any feedback on both:

https://dribbble.com/shots/2770228-Howler-js-2-0-Website

**Comment by nhoizey** [comment]
Great design!

**Comment by goldfire** [comment]
The migration guide is now available here: https://github.com/goldfire/howler.js/blob/2.0/CHANGELOG.md. We are in the final stages now, so I'm going to go ahead and close this.
